// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBA-n6Wuj4o9dBsQSVs2KMUApXRSMR0dM',
    appId: '1:887184099901:web:4bb12aba78cc51b1273854',
    messagingSenderId: '887184099901',
    projectId: 'smart-talk-877fb',
    authDomain: 'smart-talk-877fb.firebaseapp.com',
    storageBucket: 'smart-talk-877fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyWRLovKCa9L3CIHU4eCKaziGHn_fDIrU',
    appId: '1:887184099901:android:4f759a955c88e70a273854',
    messagingSenderId: '887184099901',
    projectId: 'smart-talk-877fb',
    storageBucket: 'smart-talk-877fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYCmPnfafvzzfPj7kAk9AIEWHywmLGitY',
    appId: '1:887184099901:ios:4877f2650421ba0c273854',
    messagingSenderId: '887184099901',
    projectId: 'smart-talk-877fb',
    storageBucket: 'smart-talk-877fb.appspot.com',
    iosClientId: '887184099901-q35eqivkg1iugu2llvqbi3350gettof1.apps.googleusercontent.com',
    iosBundleId: 'com.timelessfusionapps.smartTalk',
  );
}
